import './globals.css'
import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'

const vietnam = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={vietnam.className}>{children}</body>
    </html>
  )
}
